accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('', views.accounts_list,name="list"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view),
    path('accounts/',include('accounts.urls')),
    path('user/',include('user.urls')),
    path('about/', views.about_view),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'user'


urlpatterns = [
    path('signup/', views.signup_view,name="signup"),
    path('login/', views.login_view,name="login"),
    path('logout/', views.logout_view,name="logout"),

]

accounts/models.py
from django.db import models

# Create your models here.
class Accounts(models.Model):
    account_holder = models.CharField(max_length =50)
    account_number = models.CharField(unique=True,max_length = 14)
    open_date= models.DateTimeField(auto_now_add = True)


    def __str__(self):
        return self.account_holder

user/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Accounts

# Create your views here.
def accounts_list(request):
    accounts = Accounts.objects.all().order_by('open_date')
    return render(request,'accounts/accounts_list.html',{'accounts':accounts})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render
# from djangonautic import te

def home_view(request):
    return render(request,'homepage.html')
    # return HttpResponse("Hello world,this is home ")


def about_view(request):
    return render(request,'about.html')
    # return HttpResponse("Hello world ")

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


# Create your views here.
def signup_view(request):    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
       
            return redirect('accounts:list')
    else:

        form = UserCreationForm()
    return render(request,'user/signup.html',{'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid:

            user = form.get_user()
            login(request,user)
            return redirect('accounts:list')
    
    else:
        form = AuthenticationForm()
    return render(request,'user/login.html',{'form': form})


def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect('accounts:list')

accounts/templates/accounts/accounts_list.html
<html>
    <head>
        <meta charset="utf8">
        <title>Accounts</title>
    </head>
    <body>
        <h1>Accounts Page</h1>
        <div class="accounts">
            {% for account in accounts %}
            <div class="account">
                <h1><a href="">{{account.account_holder}}</a></h1>
                <p>{{account.account_number}}</p>
            </div>
            {%endfor%}

        </div>
    </body>
</html>

templates/about.html
{% extends 'base_layout.html' %}
{% block content %}
       <h1>About Page</h1>
       <p>this is our About us page  </p>
{% endblock%}

templates/base_layout.html
<html>
    <head>
        <meta charset="utf8">
        <title>Signup</title>
    </head>
    <body>
        <ul>
            <li>
                <form class="site-form" action="{% url 'user:logout'%}" method="post">
                    {%csrf_token%}
                    <button type="submit" value="Logout">Logout</button>
                </form>
            </li>
        </ul>
        {% block content %}
        {% endblock %}
    </body>
    </html>

templates/homepage.html
<html>
    <head>
        <meta charset="utf8">
        <title>Home</title>
    </head>
    <body>
        <h1>Home Page</h1>
        <p>this is our homepage </p>
    </body>
</html>

user/templates/user/login.html
<html>
    <head>
        <meta charset="utf8">
        <title>Login</title>
    </head>
    <body>
        <h1>Login Page</h1>
        <div class="accounts">
           
            <div class="account">
              <form class="site-form" action="{%url 'user:login'%}" method="post">
                {%csrf_token%}
                {{form}}
                <input type="submit" value="Login">
              </form>
            </div>

        </div>
    </body>
</html>

user/templates/user/signup.html
<html>
    <head>
        <meta charset="utf8">
        <title>Signup</title>
    </head>
    <body>
        <h1>Signup Page</h1>
        <div class="accounts">
           
            <div class="account">
              <form class="site-form" action="/user/signup/" method="post">
                {%csrf_token%}
                {{form}}
                <input type="submit" value="Signup">
              </form>
            </div>

        </div>
    </body>
</html>